# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb4e34dd3ceb2effb66d33f585d3e0661aa2aceee3bb95679a42e6bfc189da46073ff00403ee958e6f5dd097bf9cd8e0f64aa90c9e6dfe6b6d8ac7987f1485a5
  arkema:
    auth_ips:
      - 129.168.1.2
      - 123.456.789.012

test:
  secret_key_base: 75a52ac376afe4030952eeeba80324ad46f6706264aaa3787cee8598bae357a02e49812f10d36bb32fe498bc86bdb3f5df589b6fbd7cdad898812ac1e4a2daa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

passwords:
  gandi: e6xg9snifdszpqquoacm1s206fzzvnw25h4q3ohhb7kefxu4gzz5m4fkjk9x9qdbzkba1ywxblgnuj
  mysql_local:  ''
  mysql_demov1: 7F(/=<pN
  mysql_prodv1: 9Y;1CfD=MnxV
  mysql_prodv2: jnyrsylx6lodju67z
  ovh_application_key:    xVAp7bRvLqkhT1C8
  ovh_application_secret: 3yM58AYyUeURxf3Pd0x8Bnjlp8wuQVHu
  ovh_consumer_key:       5wXXxGuRM8xbd6iSrszxeEX25HFFtTAw